name: Deploy to VM

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy files to VM
        uses: appleboy/scp-action@master
        with:
          host: 64.181.180.214
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "src/*"  
          target: "/var/www/html"
